### ISSUE TITLE
Transfer Learning

### ISSUE THREAD

**Issue by grafael** [guillaumegenthial/sequence_tagging#11]
I was wondering which layer is more appropriate to transfer learning, or even if it is possible in this model.

Any thoughts about that?

**Comment by guillaumegenthial** [comment]
1. Train your whole model on some dataset with some classes
2. Reload the weights
3. Change the final layer (CRF layer, projection layer, or deeper if you want) to adapt to your new task and number of classes
4. Retrain your network

**Comment by langlanglofa** [comment]
How can i get the Glove embeddings directly then need not retrain the vector by my train data.

**Comment by grafael** [comment]
I 'll try that. Thanks
