### ISSUE TITLE
how to run this code on GPU?

### ISSUE THREAD

**Issue by erfangian** [guillaumegenthial/sequence_tagging#13]
thanks for sharing this code .
I reading your code and your blog_post but this code is run in the CPU .
how to run this code on GPU?

**Comment by guillaumegenthial** [comment]
If your tensorflow install is by default using gpu, the code would run automatically on it. If you have trouble installing TF with your GPU, I suggest stackoverflow or the official tensorflow website, where you should find existing issues along with the relevant answers.
