### ISSUE TITLE
Its getting killed but no error

### ISSUE THREAD

**Issue by search4mahesh** [guillaumegenthial/sequence_tagging#14]
I am trying to run main.py but its getting killed after sometime. I tried reduce glove file dimensions, hidden size neuron etc but its same.

Please suggest.

Thanks
Mahesh

**Comment by guillaumegenthial** [comment]
Hi Mahesh,

You probably have a problem either with
- your memory (not enough memory, RAM)
- tensorflow installation.

You should be able to find similar issues on stackoverflow along with helpful answers!

**Comment by search4mahesh** [comment]
Thanks :)
