### ISSUE TITLE
How much time it takes to train on CPU using default?

### ISSUE THREAD

**Issue by search4mahesh** [guillaumegenthial/sequence_tagging#15]
Hi,

Please let me know how much time it takes to train on CPU with default parameters.

Thanks,
Mahesh

**Comment by guillaumegenthial** [comment]
An epoch would be roughly 10x slower, so I would say 1000 seconds (15 minutes). The training process takes at least 10-15 epochs. You get a total of around 3 hours.

**Comment by search4mahesh** [comment]
Thanks :)
