### ISSUE TITLE
Where is the data set?

### ISSUE THREAD

**Issue by wangxm345566462** [guillaumegenthial/sequence_tagging#18]
Lack of test data sets, with the thesaurus, can provide a small sample of data, the code can be normal operation.

**Comment by x-ji** [comment]
Just a comment for people looking at this issue later: There is only a test data file that is included in this repo, and you're supposed to download your own dataset, e.g. CONLL2003 https://www.clips.uantwerpen.be/conll2003/ner/

**Comment by guillaumegenthial** [comment]
Good point ! It is also mentionned in the readme (https://github.com/guillaumegenthial/sequence_tagging#training-data)
