### ISSUE TITLE
Resource Exhausted when reproducing CoNLL2003

### ISSUE THREAD

**Issue by lampts** [guillaumegenthial/sequence_tagging#20]
Thank for this wonderful work. When I try to reproduce the result on CONLL2003 dataset on Tensorflow GPU instance I got this error on Char embedding + CRF layer

ResourceExhaustedError (see above for traceback): OOM when allocating tensor with shape[]
	 [[Node: train_step/beta1_power/Assign = Assign[T=DT_FLOAT, _class=["loc:@chars/_char_embeddings"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/gpu:0"](train_step/beta1_power, train_step/beta1_power/initial_value)]]

I've set batch size = 8, Tensorflow version '1.2.1'. What's wrong with that?

**Comment by lampts** [comment]
My GPU is Tesla K80.

**Comment by lampts** [comment]
My bad at preprocessing code. I gonna close it.

**Comment by letiantony** [comment]
I have met the same problem, can you share your solution? THX

**Comment by gomesraf** [comment]
@letiantony I don't know the GPU that you are using. For instance change the batch size to something < 8. Try 4 or 2

**Comment by R1994** [comment]
i met same problem,my gpu is gtx1070,batch_size is 4
