### ISSUE TITLE
`sequence_length` in `pad_sequences` for `nlevels=2`

### ISSUE THREAD

**Issue by amundle-cs** [guillaumegenthial/sequence_tagging#23]
I noticed that the `sequence_length` is not collected properly in the `pad_sequence` function: 
https://github.com/guillaumegenthial/sequence_tagging/blob/master/model/data_utils.py#L335

Shouldn't it be:
```
_, sequence_length = _pad_sequences(sequence_length, 0,  max_length_sentence)
``` 

I am slightly surprised that this hasn't caused any issues so far.

**Comment by guillaumegenthial** [comment]
Actually the purpose of this line is to pad the sequence_length parameter, in the case where we are computing the length of each word of a sentence. For instance
First sentence: "Hello" -> length = [5]
Second sentence: "Hi John" -> length = [2, 4]
what we want for the batch of this two sentences is to have sequence_length equal to
[[5, 0],
[2, 4]]
so I think I am making the right call!
