### ISSUE TITLE
Understanding the `reshape`

### ISSUE THREAD

**Issue by amundle-cs** [guillaumegenthial/sequence_tagging#25]
https://github.com/guillaumegenthial/sequence_tagging/blob/0e4e6a7e1bf87196714270a1dae8786ab2c487a8/model/ner_model.py#L132-L133

@guillaumegenthial Can you please explain the `reshape` dimensions?

**Comment by guillaumegenthial** [comment]
dynamic_rnn loops over the 1st dimension. As you want to loop over the characters, it actually is the 2nd dimension, so you need to merge the batch and sentence dimension to make the character dimension the right one.
