### ISSUE TITLE
truncate a long sentence in backpropagation

### ISSUE THREAD

**Issue by bioRichard** [guillaumegenthial/sequence_tagging#28]
hi, I have some long sentences about hundreds of words. so I think it would slow and not efficient in backprop if I use the whole sentence as one sample in training. And if I truncate a sentence into a fixed length like 20, then I can propagate the final state of the last part to the next part of the same sentence as the initial state in the forward propagation. But here is the problem, how can I calculate the probability for the whole sentence in the CRF layer?

**Comment by guillaumegenthial** [comment]
I assume you refer to this page (https://www.tensorflow.org/tutorials/recurrent#truncated-backpropagation).
For CRF, as the score is at the sequence level, that might be harder to perform. It would require passing through the dynamic programming stuff... (would require a lot of work) so I don't really know how i could help you. I see a few options:
1. either you let go of the CRF
2. you train the LSTM first and then retrain with the CRF layer without truncating
3. you train the LSTM and CRF separately and merge as in step 2. To train the CRF separately you could just store the outputs of the LSTM that you get from truncation and then feed them directly to the CRF layer as feed_dict... 

hope that helps

**Comment by bioRichard** [comment]
@guillaumegenthial thank you I'll try your advice.

**Comment by guillaumegenthial** [comment]
if you come to a solution, please share it, I'm sure it will help others!
