### ISSUE TITLE
LSTM: number of hidden layers not known

### ISSUE THREAD

**Issue by irfan-zoefit** [guillaumegenthial/sequence_tagging#29]
You did not specify the number of lstm layers. Instead there is `hidden_size_char = 100` and `hidden_size_lstm = 300`.  How we do know about the number of layers?

**Comment by guillaumegenthial** [comment]
There is just one lstm layer (just one cell).
The hidden dimension (dimension of the hidden vector that passes through the time steps) is specified  with the above.
You can try to add more layers but I guess this would just increase the computational time without gaining much improvement.
