### ISSUE TITLE
Indices Error in CRF

### ISSUE THREAD

**Issue by rikkuporta** [guillaumegenthial/sequence_tagging#32]
Hi!
I dont know if you can help me, but Ill ask.
I created my own pipeline to generate data in the format that is needed by your network, without needing to save it in a file or something like that. Right now Im not using any word embeddings, and the network is training and loss is falling. Until at some point in the training an error comes up:

InvalidArgumentError (see above for traceback): indices[2,5] = 1716 is not in [0, 1681)
	 [[Node: crf/Gather_1 = Gather[Tindices=DT_INT32, Tparams=DT_FLOAT, validate_indices=true, _device="/job:localhost/replica:0/task:0/cpu:0"](crf/Reshape_3, crf/add_2)]]

Which happens at the tf.contrib.crf.crf_log_likelihood

Do you have any idea what this could be?

**Comment by rikkuporta** [comment]
Nevermind, I found it, it was just a index shift, because my tags started at 1 instead of 0. The error message was just to cryptic for me.

**Comment by guillaumegenthial** [comment]
great you found out! closing the issue.
