### ISSUE TITLE
No generalization while inferring

### ISSUE THREAD

**Issue by rikkuporta** [guillaumegenthial/sequence_tagging#33]
Ok, Ive got another issue, which I am not sure how to solve.
So everything works so far with my own pipeline and dataset but I ran into a strange problem, and I dont know exactly what could be wrong.
Basically, when I send something to the Model to create tags for, it returns them without problem. I'm running one instance of the original model (still, on my dataset) and one model with my pipeline.

The strange thing that happens is when I try to predict a sequence it has not learned. 
For example: Show me a red dress.

Neither color nor dress are within the dataset, but when I run this example on the original model, it receives (more or less) the correct entities. Which is good.
If I run this example on my pipeline, it only receives O tags. 
Which is just really strange behaviour. Do you have any idea what or why it could be?

**Comment by guillaumegenthial** [comment]
It seems like the problem is not about the model but rather about your data and how you feed it to the model. Maybe check the vocabulary, the preprocessing (lowercase?) etc.!
