### ISSUE TITLE
99.01 % accuracy 

### ISSUE THREAD

**Issue by arun-taiger** [guillaumegenthial/sequence_tagging#36]
Epoch 15 out of 15
281/281 [==============================] - 350s - train loss: 0.1390     
acc 99.91 - f1 99.32
- new best score!
I am getting  f1 99.32, which is not right with same configuration.

**Comment by guillaumegenthial** [comment]
Which dataset do you use?
I reran everything with the latest release of TF, and everything still holds together. (on CoNLL2003, ~94 on dev, ~90 on test).
Also keep in mind that the scores are computed on the dev set.

**Comment by guillaumegenthial** [comment]
closing the issue.
