### ISSUE TITLE
where is the tagged test file

### ISSUE THREAD

**Issue by 7belrhalmia** [guillaumegenthial/sequence_tagging#39]
Hey,

when you execute python evaluate.py, I was wondering if a tagged test file was generated in the same format of the training dataset. like not only getting the accuracy but also the test file with the tagged results.

**Comment by guillaumegenthial** [comment]
Hi @7belrhalmia,
No file is actually generated during evaluation. However, if you want to write a file, you can easily modify the `run_evaluate` function in the `ner_model.py` file.
