### ISSUE TITLE
About dataset and pre-trained word embedding

### ISSUE THREAD

**Issue by theanhle** [guillaumegenthial/sequence_tagging#4]
Could you mind explaining what "trimmed_filename" is used for, and how I can create it (or it is created from the original file: glove_filename)
`trimmed_filename = "data/glove.6B.{}d.trimmed.npz".format(dim)`
Could you giving me the links to the dataset? I downloaded dataset from conll2003 and ran build_data.py, then got an error:
`File "C:/Users/dragon/sequence_tagging-master/build_data.py", line 49, in <module>
    build_data(config)
  File "C:/Users/dragon/sequence_tagging-master/build_data.py", line 25, in build_data
    vocab_words, vocab_tags = get_vocabs([train, dev, test])
  File "C:\Users\dragon\sequence_tagging-master\data_utils.py", line 87, in get_vocabs
    for words, tags in dataset:
  File "C:\Users\dragon\sequence_tagging-master\data_utils.py", line 55, in __iter__
    word, tag = line.split(' ')
ValueError: too many values to unpack (expected 2)`
Thank you in advance!

**Comment by guillaumegenthial** [comment]
1. Data: if you want to use CoNLL2003 data, you need to download the tag from the conll2003 webpage and the articles form reuters. Everything is explained on the conll2003 webpage. Finally, you need to make sure that your data files are in the format discribed in the REAME.md
2. Embeddings: you need to download the glove wordvectors (and maybe rename the file location in the config.py file)

Once you have the embeddings and the data files, you run build_data.py that produces the trimmed word glove vectors + the vocabularies (tags, words, characters)
I hope this helps.
