### ISSUE TITLE
TypeError: data type not understood

### ISSUE THREAD

**Issue by Jonida88** [guillaumegenthial/sequence_tagging#49]
Have someone a idee why i am getting this error when runing build_data...... 

```
Building vocab...
-done.33970tokens
Building vocab...
-done.400000 tokens
Writing vocab..
-done.7398 tokens
Writing vocab...
-done.28227 tokens

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-46-c239750804c9> in <module>()
     40 
     41 if __name__ == "__main__":
---> 42     main()

<ipython-input-46-c239750804c9> in main()
     31     vocab = load_vocab(config.filename_words)
     32     export_trimmed_glove_vectors(vocab, config.filename_glove,
---> 33                                 config.filename_trimmed, config.dim_word)
     34 
     35     # Build and save char vocab

~\ML\data_utils.py in export_trimmed_glove_vectors(vocab, filename_glove, filename_trimmed, dim)
    157 def export_trimmed_glove_vectors(vocab, filename_glove, filename_trimmed, dim):
    158 
--> 159     embeddings = np.zeros([len(vocab),dim])
    160     with open(filename_glove,"r",encoding="utf-8") as f:
    161         for line in f:

TypeError: data type not understood
```

**Comment by guillaumegenthial** [comment]
Hi @Jonida88!
Check your numpy version but it might be the case that for some reasons it does not understand the shape given as a list, change it to a tuple like (len(vocab), dim) instead of [len(vocab), dim]

**Comment by Jonida88** [comment]
Hi @guillaumegenthial glad that you was answering me i was able to solve it but now i have an other issue i am runing the build_data without error so this mean:

```
> Building vocab...
-done.33970tokens
Building vocab...
-done.400000 tokens
Writing vocab..
-done.7398 tokens
Writing vocab..
-done.28227 tokens
Writing vocab..
-done.85 tokens
```

but when i open the file I have this issue:
```
> Error! C:\Users\admin\ML\data\glove.6B.300d.trimmed.npz is not UTF-8 encoded
> Saving disabled.
> See Console for more details.

```
the code 
`np.savez_compressed(filename_trimmed, embeddings=embeddings)
    

def get_trimmed_glove_vectors(filename_trimmed):
    try:
        with np.load(filename_trimmed) as data:
            return data["embeddings"]
    except IOError:
        raise MyIOError(filename_trimmed)`

any idea... thanks for your help...

**Comment by DimejiOladepo** [comment]
I also had this issue. I upgraded my Tensorflow to 2.0.0 and numpy to 1.16.4. 

For your new problem, consider saving your glove embedding as a UTF-8 txt file. Opening it in this format doesn't give issues.

I hope this helps.
