### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by sanjayb678** [guillaumegenthial/sequence_tagging#50]
Hi Guillaume,

I'm simply running the code as is. Is it something to do with the python version ?

class IncrementalDecoder(codecs.IncrementalDecoder):
25 def decode(self, input, final=False):
---> 26 return codecs.ascii_decode(input, self.errors)[0]
27 
28 class StreamWriter(Codec,codecs.StreamWriter):

UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 123: ordinal not in range(128)

**Comment by guillaumegenthial** [comment]
Hope you solved it!
