### ISSUE TITLE
F1 score at 79 after 15 epochs

### ISSUE THREAD

**Issue by samyam** [guillaumegenthial/sequence_tagging#69]
Hi Guillaume, 

I am not able to reproduce the 90+ F1 score that you mention with Cornll2003 eng. At the end of 15 epochs I am at F1 score of 79 with all the parameters set to as is in the config file. Do I need to change any of the parameters to get the 90+ F1 score?

Best,
Samyam

**Comment by guillaumegenthial** [comment]
You don't need to change any of the parameters.
But make sure you use the right tagging scheme (IOBES) and the best vectors available (try GloVe 6B and 840B).
I wrote a better implementation and extensively tested it. It's available here https://github.com/guillaumegenthial/tf_ner
